#!/bin/bash

gituser=git
githost=127.0.0.1
gitpath=/srv/git

projectname=$(basename $PWD)
projectdirname="${projectname}.git"
projectdirpath="${gitpath}/${projectdirname}"
gituserhost=${gituser}@${githost}

if ssh -q ${gituserhost} [[ -d "${projectdirpath}" ]] ; then
	echo -e "\e[31mРепозиторий ${projectname} уже существует\e[0m"
else
	git init
	git add *
	git commit -m 'Init'
	git clone --bare . $projectdirname
	scp -r $projectdirname "${gituserhost}:${gitpath}"
	rm -rf $projectdirname
	git remote add origin "${gituserhost}:${projectdirpath}"
	git push origin master
	echo -e "\e[32mРепозиторий ${projectname} успешно создан\e[0m"
fi
